# Generated by Django 4.2.2 on 2024-07-21 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_graphics_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphics',
            options={},
        ),
        migrations.RemoveField(
            model_name='graphics',
            name='description',
        ),
        migrations.RemoveField(
            model_name='graphics',
            name='image',
        ),
        migrations.RemoveField(
            model_name='graphics',
            name='name',
        ),
        migrations.RemoveField(
            model_name='graphics',
            name='status',
        ),
        migrations.AddField(
            model_name='graphics',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphics',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
