# Generated by Django 4.2.2 on 2024-07-21 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_graphics_options_remove_graphics_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
