# Generated by Django 4.2.2 on 2024-07-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_graphics_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
