# Generated by Django 4.2.2 on 2024-07-21 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_graphics_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphics',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='graphics',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphics',
            name='image',
            field=models.ImageField(upload_to='graphics/'),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], max_length=10),
        ),
    ]
