# Generated by Django 4.2.2 on 2024-07-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_title_graphics_name_graphics_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
