# Generated by Django 4.2.2 on 2024-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
