# Generated by Django 4.2.2 on 2024-02-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='phone',
        ),
    ]
