# Generated by Django 4.2.2 on 2024-02-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_rename_contact_contact_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'Contact'},
        ),
    ]
